# Generated by Django 3.2.10 on 2021-12-14 12:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Название')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('candidate', models.CharField(blank=True, default='', max_length=300, verbose_name='Название')),
                ('complete', models.BooleanField(default=False, verbose_name='Подключение к интернету')),
                ('start', models.BooleanField(default=False, verbose_name='Подключение к интернету')),
                ('public_key', models.TextField(blank=True, default='', verbose_name='Открытый ключ')),
                ('private_key', models.TextField(blank=True, default='', verbose_name='Закрытый ключ')),
            ],
            options={
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'Голосования',
            },
        ),
        migrations.CreateModel(
            name='VoteResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.votemodel')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='CandidateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='ФИО')),
                ('type', models.CharField(blank=True, default='', max_length=100, verbose_name='Тип')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('group', models.CharField(blank=True, default='', max_length=100, verbose_name='Партия')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/candidate/', verbose_name='Фото')),
                ('vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.votemodel')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
            },
        ),
    ]
