# Generated by Django 3.2.10 on 2021-12-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatemodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='candidatemodel',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='votemodel',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Завершить голосование'),
        ),
        migrations.AlterField(
            model_name='votemodel',
            name='start',
            field=models.BooleanField(default=False, verbose_name='Начать голосование'),
        ),
    ]
