# Generated by Django 3.2.10 on 2021-12-14 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0002_auto_20211214_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.IntegerField(max_length=300, verbose_name='Значение голоса')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='votes.votemodel')),
            ],
            options={
                'verbose_name': 'Голос пользователя',
                'verbose_name_plural': 'Голоса Пользователей',
            },
        ),
    ]
