# Generated by Django 3.2.10 on 2021-12-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_voiceuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='votemodel',
            name='p',
            field=models.IntegerField(blank=True, default=1, verbose_name='p'),
        ),
        migrations.AddField(
            model_name='votemodel',
            name='q',
            field=models.IntegerField(blank=True, default=1, verbose_name='q'),
        ),
        migrations.AlterField(
            model_name='voiceuser',
            name='voice',
            field=models.IntegerField(verbose_name='Значение голоса'),
        ),
    ]
