# Generated by Django 3.2.10 on 2021-12-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20211215_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteResultModel',
        ),
    ]
