# Generated by Django 3.2.10 on 2021-12-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_delete_voteresultmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashVoiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_hash', models.IntegerField(default=0, verbose_name='Хеш значения голоса')),
                ('voice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='votes.voiceuser')),
            ],
            options={
                'verbose_name': 'Хеш голоса пользователя',
                'verbose_name_plural': 'Хеши Голосов Пользователей',
            },
        ),
    ]
