# Generated by Django 3.2.10 on 2021-12-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_hashvoiceuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashvoiceuser',
            name='voice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votes.voiceuser'),
        ),
    ]
