# Generated by Django 3.2.10 on 2021-12-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0007_alter_hashvoiceuser_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashvoiceuser',
            name='voice_hash',
            field=models.TextField(default=0, verbose_name='Хеш значения голоса'),
        ),
    ]
