# Generated by Django 3.2.10 on 2021-12-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Имя')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Номер телефона')),
                ('password', models.CharField(default='', max_length=100, verbose_name='Пароль')),
                ('login', models.CharField(blank=True, max_length=100, verbose_name='Логин')),
                ('token', models.CharField(blank=True, max_length=100, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
